feat: resolver rebased
iotaledger/uni-resolver-driver-iota pull request #5
Opened 2024-11-18 15:10 UTC by itsyaasir

# Description of change

This pull request includes several significant changes aimed at updating the resolver to the latest rebased IOTA.

Changes include:
- Updating all the dependencies
- Refactor for the tests

## Links to any relevant issues

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- [x] Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have updated the CHANGELOG.md, if my changes are significant enough

2024-11-27 11:33 UTC, UMR1352 requested changes
I'd probably just drop the use of `identity_iota::resolver::Resolver` in favor of a custom structure (`HashMap`??) to get the right client for the right network.
If `identity_iota_core::rebased::migration::identity::get_identity` is exposed by `identity_iota` I'd probably use that to resolve since it returns a `Result<Option<Identity>>` allowing you to easily handle 500 error as well as 404 (without having to look into the error message).

2024-11-27 11:33 UTC, UMR1352 commented on tests/did_resolution.rs
:eye::eye: naughty :eye::eye:
You can't change a test just to make it work. When a DID is missing the right error to return is 404, if something goes wrong during resolution only then you return a 500.

2024-11-27 11:38 UTC, UMR1352 commented on Cargo.lock
Do we have to track this file?

2024-12-02 17:40 UTC, itsyaasir commented on tests/did_resolution.rs
I thought this was changed in the identity core package itself; but will investigate it more

2024-12-02 17:41 UTC, itsyaasir commented on Cargo.lock
Not reallly! I might have added it accidentally

2024-12-02 18:22 UTC, itsyaasir commented
> I'd probably just drop the use of `identity_iota::resolver::Resolver` in favor of a custom structure (`HashMap`??) to get the right client for the right network. If `identity_iota_core::rebased::migration::identity::get_identity` is exposed by `identity_iota` I'd probably use that to resolve since it returns a `Result<Option<Identity>>` allowing you to easily handle 500 error as well as 404 (without having to look into the error message).

I have opted to use the `HashMap` structure; couple of things I changed was the did network tag to `unknwn` since the devnet was returning this `unknwn` but IIRC you are working on this so will change as soon as you are done.

2024-12-03 09:31 UTC, UMR1352 commented
@itsyaasir good job! Do you mind waiting a bit before merging this? RN we are reworking a bit DID resolution on Rebased and I feel these changes should account for that as well.

2024-12-09 14:39 UTC, UMR1352 requested changes

2024-12-09 14:39 UTC, UMR1352 commented on src/lib.rs
>          })?;
Taking back what I said in a previous review comment. Unfortunately we can't just use `get_identity` as that only queries `OnChainIdentity`s and doesn't for instance resolve unmigrated aliases or migrated identities. We gotta go back to the previous implementation using `client.resolve_did` but making sure we return a 404 when the document is not found

2024-12-09 16:03 UTC, itsyaasir commented on src/lib.rs
>          })?;
I have already redone it, please do take a look when you have the time.

2024-12-10 09:40 UTC, UMR1352 approved these changes

2024-12-10 09:41 UTC, UMR1352 approved these changes
Make sure the tests run succesfully

2024-12-10 16:21 UTC, UMR1352 commented on tests/common/mod.rs
> +    let _ = request_faucet_funds(address).await;
Mmmm not sure if this is desirable... Can't we test on a localnet instead?

2024-12-10 19:04 UTC, itsyaasir commented on tests/common/mod.rs
> +    let _ = request_faucet_funds(address).await;
We can but we will have to publish the package which is not available here.

2024-12-10 19:05 UTC, itsyaasir commented on tests/common/mod.rs
> +    let _ = request_faucet_funds(address).await;
Anyone even what I did didn't work.

2025-06-17 14:24 UTC, merged